apiVersion: apps/v1  #kubectl api-versions 可以通过这条指令去看版本信息
kind: Deployment # 指定资源类别
metadata: #资源的一些元数据
  name: provider-service-2 #deloyment的名称
  namespace: xujiayu
  labels:
    app: provider-service-2  #标签
spec:
  replicas: 2 #创建pod的个数
  selector:
    matchLabels:
      app: provider-service-2 #满足标签为这个的时候相关的pod才能被调度到
  template:
    metadata:
      labels:
        app: provider-service-2
        # apphub.volcengine.com/hostport-exposed: enabled
        # apphub.volcengine.com/ploto-enabled: enabled
        # apphub.volcengine.com/ploto-domain: luomin
        # apphub.volcengine.com/ploto-system: ss1
        # apphub.volcengine.com/service-name: provider-service-2
        # apphub.volcengine.com/service-version: v1
      annotations:
        # apphub.volcengine.com/consul-server-addresses: 172.19.35.91:31500
        # apphub.volcengine.com/ploto-core-address: 172.19.35.91:30882
        # prometheus.io/jmx: /metrics
        # prometheus.io/path: /metrics
        # prometheus.io/port: "5555"
        # prometheus.io/scrape: "true"
        # prometheus.io/type: JVM
    spec:
      containers:
        - name: provider-service-2
          image: vecps.cargo.io/infcprelease/test-springboot:provider-service-test2-test 
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 6702
            - containerPort: 5555