kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: mysql-class
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: release, operator: In, values: [stable]}