apiVersion: apps/v1  #kubectl api-versions 可以通过这条指令去看版本信息
kind: Deployment # 指定资源类别
metadata: #资源的一些元数据
  name: web-one #deloyment的名称
  namespace: xujiayu
  labels:
    app: web-one  #标签
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '5555'
spec:
  replicas: 1 #创建pod的个数
  selector:
    matchLabels:
      app: web-one #满足标签为这个的时候相关的pod才能被调度到
  template:   
    metadata:
      labels:
        app: web-one
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '5555'
    spec:  
      containers:
        - name: web-one
          image: vecps.cargo.io/infcprelease/web-one:test1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 5555
          env:
            - name: JAVA_OPTS
              value: >-
                -javaagent:/jmx_prometheus_javaagent-0.16.1.jar=5555:/prometheus-jmx-config.yaml
          