apiVersion: v1
kind: Service
metadata:
  name: web-one-svc
  namespace: xujiayu
spec:
  selector:
    app: web-one
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: tomcat
    - protocol: TCP
      port: 5555
      targetPort: 5555
      name: metrics