apiVersion: v1
kind: Pod
metadata: 
  name: cm-test-pod
spec: 
  containers:
    - name: cm-test-container
      image: busybox
      command: ["/bin/sh", "-c","env"]
      #envFrom: 
      #- configMapRef
        #name: cm-appvars
      #env: 
      #- name: APPLOGLEVEL
      #  valueFrom:
      #    configMapKeyRef: 
      #      name: cm-appvars
      #      key: apploglevel
      #- name: APPDATADIR
      #  valueFrom: 
      #    configMapKeyRef:
      #      name: cm-appvars
      #      key: appdatadir
  restartPolicy: Never