apiVersion: v1
kind: Pod
metadata:
  name: downap-test-container-vars-002
  labels:
    name: downap-test-container-vars-002
spec:
  containers:
    - name: downap-test-container-vars-002
      image: busybox
      imagePullPolicy: Never
      command: ["sh","-c"]
      args:
      - while true; do
          echo -en '\n';
          printenv MY_CPU_REQUEST MY_CPU_LIMIT;
          printenv MY_MEM_REQUEST MY_MEM_LIMIT;
          sleep 3600;
        done;
      resources:
        requests:
          memory: 10Mi
          cpu: 125m
        limits:
          memory: 10Mi
          cpu: 125m
      env:
        - name: MY_CPU_REQUEST
          valueFrom:
            resourceFieldRef: 
              containerName: downap-test-container-vars-002
              resource: requests.cpu
        - name: MY_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: downap-test-container-vars-002
              resource: limits.cpu
        - name: MY_MEM_REQUEST
          valueFrom: 
            resourceFieldRef:
              containerName: downap-test-container-vars-002
              resource: requests.memory
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef: 
              containerName: downap-test-container-vars-002
              resource: limits.memory
  restartPolicy: Never
            