apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loop
  name: loop
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: loop
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loop
    spec:
      containers:
        - args:
            - while true; do curl http://service-a:8081; sleep 1; done
          command:
            - /bin/sh
            - -c
            - --
          image: cr-cn-beijing.volces.com/insight-dfx/netshoot
          imagePullPolicy: IfNotPresent
          name: loop
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30

