apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    livenessProbe:
      tcpSocket: 
        port: 80
      initialDelaySeconds: 30
      timeoutSeconds: 1
    readinessProbe:
      httpGet:
        path: /_status/health
        port: 80
      
