apiVersion: v1
kind: Pod
metadata:
  labels:
    test: test-liveness
  name: test-liveness
spec:
  containers:
    - name: test-liveness
      image: gcr.io/google_containers/busybox
      args:
        - /bin/sh
        - -c
        - echo ok > /tmp/health; sleep 10; rm -rf /tmp/health; sleep 600
      livenessProbe:
        exec: 
          command:
            - cat
            - /tmp/health
        initialDelaySeconds: 15
        timeoutSeconds: 1