apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: springboot-deploy-local-pvc
  namespace: xujiayu
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: java-agent-local-storage
  resources:
    requests:
      storage: 1Gi