apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: default-privileged
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - "*"
  volumes:
    - "*"
  hostNetwork: true
  hostPorts:
    - max: 65535
      min: 0
  hostIPC: true
  hostPID: true
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
