apiVersion: v1
kind: Service
metadata:
  name: extend-svc
  namespace: xujiayu
spec:
  clusterIP: None
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx

# ---

# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: extend-svc-3
#   namespace: xujiayu
# subsets:
#   - addresses:
#     - ip: 192.168.56.103
#     ports:
#     - port: 80